#!/usr/bin/env bash
#Version 1.0

# Intended to take a MVK ripped from a DVD and convert it to decent-video H.265

source /usr/local/lib/colors
function printx {
  printf "${YELLOW}$1${NOCOLOR}\n"
}

STMT=$(basename $0)

if [[ $# < 2 ]]; then
  printx "Syntax: $STMT '<filepath>' '<outpath>'\nWhere:  <filepath> is the FQPN for the file to be processed and <outpath>\n        is the name of the path where the output file should be placed.\n"
  exit
fi

FILEPATH=$1
OUTPATH=$2
FILENAME=${FILEPATH##*/}
#echo FILEPATH=${FILEPATH}
#echo FILENAME=${FILENAME}
#echo OUTPATH=${OUTPATH}
#exit

ENCODING=hevc_nvenc
CRF=20
BITRATE=384k

ffmpeg -i "$FILEPATH" -c:v $ENCODING -crf $CRF -preset slow -rc vbr_hq -c:a aac -b:a $BITRATE -c:s copy "$OUTPATH/$FILENAME"
